### ISSUE TITLE
请问该插件是否支持xcode 8

### ISSUE THREAD

**Issue by CoderSQ** [bang590/JSPatchX#4]
目前在xocode8下面安装该插件后，编辑main.js，无法看到相关提示信息。

**Comment by bang590** [comment]
目前不支持，待解决

**Comment by zongren** [comment]
+1

**Comment by jiaxw32** [comment]
升级到XCode8用不了，有没有其他解决方案

**Comment by bang590** [comment]
请参考这篇文章http://www.jianshu.com/p/dc2fc2a680fc

**Comment by CoderSQ** [comment]
我提出问题后，打包一个unsigned的XCODE，用这个包就可以使用bang的插件了，不过经常会失效 ~！~
