### ISSUE TITLE
添加了JSPatchX

### ISSUE THREAD

**Issue by HikingMan** [bang590/JSPatchX#6]
添加了JSPatchX之后，我去掉了xcode对于冒号的缩进，但是页面还是乱
![image](https://cloud.githubusercontent.com/assets/13775067/21000599/c9ffb822-bd56-11e6-9b43-8bbd36c30b89.png)

bang哥有空给看下吧，写起来很痛苦

![image](https://cloud.githubusercontent.com/assets/13775067/21045548/d50b5d76-be3b-11e6-9f4c-8e8715f84ac9.png)

**Comment by bang590** [comment]
你写完后在 http://jspatch.com/Tools/jslint 这里格式化美化下吧……

**Comment by HikingMan** [comment]
格式化之后是好的，但是复制进xcode中的js文件，格式还是原来的样子。有没有其他的方法，能够在xcode中格式正确的。

**Comment by bang590** [comment]
你复制时可以选这个
![image](https://cloud.githubusercontent.com/assets/329480/21141074/3240a00e-c176-11e6-8ede-16e8cbc458c3.png)

**Comment by HikingMan** [comment]
恩，这样页面就可以了。感谢bang哥 @bang590
